---
- hosts: all:!*openbsd*
  gather_facts: no
  remote_user: hlk
  pre_tasks:
    - name: verify python installed
      raw: dpkg -s python-simplejson > /dev/null 2>&1
      register: python_installed
      ignore_errors: True

    - name: install python
      raw: sudo apt-get -y install python python-simplejson
      when: python_installed|failed
